---
title: "Data Import"
output: github_document
---

This file is for doing data import.

```{r}
library(tidyverse)
```


We'll import our first dataset.

```{r}
litters_df = read_csv(file="data_import_examples/FAS_litters.csv", na= c("", "NA", "."))

litters_df = janitor::clean_names(litters_df)
litters_df
```

We now can import our second dataset, pups.

```{r}
pups_df = read_csv(file="data_import_examples/FAS_pups.csv", skip=3, na=c("","na","."))

pups_df = janitor::clean_names(pups_df)
pups_df
```


Skimming

```{r}
skimr::skim(pups_df)
```


You can use view() to look at a whole dataframe.


# Excel

Jenny Bryan made readxl to solve the excel problems

```{r}
library(readxl)
mlb_df = read_excel("data_import_examples/mlb11.xlsx")
mlb_df
```


```{r}
lotr_df = read_excel("data_import_examples/LotR_Words.xlsx", range="B3:D6")
lotr_df
```


```{r}
library(haven)

pulse_df = read_sas("data_import_examples/public_pulse_data.sas7bdat")
pulse_df = janitor::clean_names(pulse_df)
head(pulse_df, 5)
```

```{r}
pups_df_base = read.csv("data_import_examples/FAS_pups.csv")
pups_df_base
```

Won't show: lazy about variable names and slow for big datasets



